# Generated by Django 3.2.15 on 2022-09-15 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(max_length=200)),
                ('Adhaar_no', models.IntegerField(blank=True, null=True)),
                ('adhaar_img', models.ImageField(blank=True, null=True, upload_to='adhaarimg')),
                ('password', models.TextField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
    ]
