# Generated by Django 3.2.15 on 2022-09-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='adhaar_img',
        ),
    ]
