# Generated by Django 4.0.6 on 2022-09-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_file_adhaar_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='userregister',
            old_name='name',
            new_name='user_id',
        ),
    ]
