# Generated by Django 3.2.15 on 2022-10-04 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20221004_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Iam_hiring',
            new_name='employee_status',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='Looking_for_job',
        ),
    ]
