# Generated by Django 3.2.15 on 2022-10-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20221004_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_id',
            field=models.CharField(max_length=200),
        ),
    ]
