# Generated by Django 4.0.6 on 2022-11-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_address_employee_district_and_more'),
        ('api', '0008_auto_20221004_1328'),
    ]

    operations = [
    ]
